
SUPABASE_URL = "https://pthuquoyvribokopvihm.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0aHVxdW95dnJpYm9rb3B2aWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDYzMDIsImV4cCI6MjA3MjcyMjMwMn0.RlcVPbhnMllKm6rjO3u6qxzXjtZHNwW58imVA3c_mws"
COOP_NAME = "NAAT Multipurpose Cooperative JOSTUM"
